# Generated by Django 3.1.7 on 2021-04-06 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20210406_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.package'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
